language: node_js
node_js:
- '0.11'
- '0.10'
env:
  - TEST_DIR=api IS_TRAVIS_RUN=yes
script: cd $TEST_DIR && npm install && npm test
services:
- mongodb
before_script:
  - sleep 15
  - mongo --eval 'use test_db'
  - mongo test_db --eval 'db.addUser("travis", "test");'