language: node_js
node_js:
- '0.11'
- '0.10'
env:
  - TEST_DIR=api IS_TRAVIS_RUN=yes
script: cd $TEST_DIR && npm install && npm test
services:
- mongodb
before_script:
  - sleep 5
  - mongo mydb_test --eval 'db.addUser("travis", "test");'